### ISSUE TITLE
Undefined Exception for Case Statement Syntax Error

### ISSUE THREAD

**Issue by hjkatz** [Sententiaregum/eslint-plugin-varspacing#26]
### Description of the issue

Cannot call method 'indexOf' of undefined.

### Steps to reproduce

```javascript
var test = 'banana';
switch( test )
{
    case 'Hello':
        test2 = 15; 
}
```

### Expected behavior

No exception to be thrown so the syntax error bubbles up.

### Additional information

Here's the full stack trace:

```
Cannot call method 'indexOf' of undefined
TypeError: Cannot call method 'indexOf' of undefined
    at module.exports (/usr/lib/node_modules/eslint-plugin-varspacing/lib/util/findNextPunctuators.js:23:22)
    at EventEmitter.expressionCheck (/usr/lib/node_modules/eslint-plugin-varspacing/lib/rules/var-spacing.rule.js:44:7)
    at EventEmitter.emit (events.js:117:20)
    at NodeEventGenerator.enterNode (/usr/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/usr/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/usr/lib/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/usr/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/usr/lib/node_modules/eslint/lib/util/traverser.js:36:33)
```

**Comment by Ma27** [comment]
can confirm this. Will try to fix it in the next time :)

**Comment by hjkatz** [comment]
Awesome response time, thanks!

**Comment by Ma27** [comment]
I've submitted a patch for this to master.
My assumption is that the switch-case looks a bit different when traversing through tokens created by the tokenizer of ESLint, therefore some parts looked different which cased your issue (the `lib/util/findNextPunctuators` looks for assignments that will be validated after that).
Would be great if you could test the stuff on master, before I'll release this...

**Comment by Ma27** [comment]
checked it another time @hjkatz, releasing now :)

**Comment by Ma27** [comment]
removed from project as it's released and not in active development
